In [104]:
#### Imports ####
import pandas as pd
import requests

In [110]:
# Webscrape Dataframes
url1 = 'https://www.basketball-reference.com/awards/awards_2024.html'
url2 = 'https://www.basketball-reference.com/leagues/NBA_2024_totals.html'
url3 = 'https://www.basketball-reference.com/leagues/NBA_2024_per_game.html'
url4 = 'https://www.basketball-reference.com/leagues/NBA_2024_advanced.html'

mvp = pd.read_html(url1, header=1, attrs={'id':'mvp'})[0]
totals = pd.read_html(url2, header=0, attrs={'id':'totals_stats'})[0]
per_game = pd.read_html(url3, header=0, attrs={'id':'per_game_stats'})[0]
advanced = pd.read_html(url4, header=0, attrs={'id':'advanced'})[0]

In [221]:
mvp_ = mvp.drop(columns=['Rank', 'Age', 'Tm', 'First', 'Pts Won', 'Pts Max'], axis=1).\
        rename(columns={'MP':'MPPG', 'PTS':'PTSPG', 'TRB':'TRBPG', 'AST':'ASTPG', 'STL':'STLPG', 'BLK':'BLKPG'}).\
        fillna(0)
mvp_

,Player,Share,G,MPPG,PTSPG,TRBPG,ASTPG,STLPG,BLKPG,FG%,3P%,FT%,WS,WS/48
0,Nikola Jokić,0.935,79,34.6,26.4,12.4,9.0,1.4,0.9,0.583,0.359,0.817,17.0,0.299
1,Shai Gilgeous-Alexander,0.646,75,34.0,30.1,5.5,6.2,2.0,0.9,0.535,0.353,0.874,14.6,0.275
2,Luka Dončić,0.572,70,37.5,33.9,9.2,9.8,1.4,0.5,0.487,0.382,0.786,12.0,0.220
3,Giannis Antetokounmpo,0.194,73,35.2,30.4,11.5,6.5,1.2,1.1,0.611,0.274,0.657,13.2,0.246
4,Jalen Brunson,0.143,77,35.4,28.7,3.6,6.7,0.9,0.2,0.479,0.401,0.847,11.2,0.198
5,Jayson Tatum,0.087,74,35.7,26.9,8.1,4.9,1.0,0.6,0.471,0.376,0.833,10.4,0.189
6,Anthony Edwards,0.018,79,35.1,25.9,5.4,5.1,1.3,0.5,0.461,0.357,0.836,7.5,0.130
7,Domantas Sabonis,0.003,82,35.7,19.4,13.7,8.2,0.9,0.6,0.594,0.379,0.704,12.6,0.206
8,Kevin Durant,0.001,75,37.2,27.1,6.6,5.0,0.9,1.2,0.523,0.413,0.856,8.3,0.142

In [222]:
totals_ = totals.drop(['Rk', 'Age', 'Team', 'Pos', 'Awards'], axis=1).\
                drop_duplicates(subset=['Player'], keep='first', ignore_index=True).\
                iloc[:-1].fillna(0)
totals_

,Player,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl
0,Luka Dončić,70.0,70.0,2624.0,804.0,1652.0,0.487,284.0,744.0,0.382,520.0,908.0,0.573,0.573,478.0,608.0,0.786,59.0,588.0,647.0,686.0,99.0,38.0,282.0,149.0,2370.0,21.0
1,Shai Gilgeous-Alexander,75.0,75.0,2553.0,796.0,1487.0,0.535,95.0,269.0,0.353,701.0,1218.0,0.576,0.567,567.0,649.0,0.874,65.0,350.0,415.0,465.0,150.0,67.0,162.0,184.0,2254.0,0.0
2,Giannis Antetokounmpo,73.0,73.0,2567.0,837.0,1369.0,0.611,34.0,124.0,0.274,803.0,1245.0,0.645,0.624,514.0,782.0,0.657,196.0,645.0,841.0,476.0,87.0,79.0,250.0,210.0,2222.0,10.0
3,Jalen Brunson,77.0,77.0,2726.0,790.0,1648.0,0.479,211.0,526.0,0.401,579.0,1122.0,0.516,0.543,421.0,497.0,0.847,43.0,235.0,278.0,519.0,70.0,13.0,186.0,144.0,2212.0,0.0
4,Nikola Jokić,79.0,79.0,2737.0,822.0,1411.0,0.583,83.0,231.0,0.359,739.0,1180.0,0.626,0.612,358.0,438.0,0.817,223.0,753.0,976.0,708.0,108.0,68.0,237.0,194.0,2085.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,Danny Green,2.0,0.0,18.0,0.0,2.0,0.000,0.0,1.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,0.000,0.0,2.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
568,Ron Harper Jr.,1.0,0.0,4.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0
569,Justin Jackson,2.0,0.0,1.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
570,Dmytro Skapintsev,2.0,0.0,2.0,0.0,1.0,0.000,0.0,0.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
571,Javonte Smart,1.0,0.0,1.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [223]:
per_game_ = per_game.drop(['Rk', 'Age', 'Team', 'Pos', 'Awards'], axis=1).\
                    drop_duplicates(subset=['Player'], keep='first', ignore_index=True).\
                    rename(columns={'MP':'MPPG', 'FG':'FGPG', 'FGA':'FGAPG', '3P':'3PPG', '3PA':'3PAPG','2P':'2PPG', '2PA':'2PAPG', 'FT':'FTPG', 'FTA':'FTAPG',
                                    'ORB':'ORBPG', 'DRB':'DRBPG', 'TRB':'TRBPG', 'AST':'ASTPG', 'STL':'STLPG', 'BLK':'BLKPG', 'TOV':'TOVPG',
                                    'PF':'PFPG', 'PTS':'PTSPG'}).\
                    fillna(0).iloc[:-1]
per_game_

,Player,G,GS,MPPG,FGPG,FGAPG,FG%,3PPG,3PAPG,3P%,2PPG,2PAPG,2P%,eFG%,FTPG,FTAPG,FT%,ORBPG,DRBPG,TRBPG,ASTPG,STLPG,BLKPG,TOVPG,PFPG,PTSPG
0,Joel Embiid,39.0,39.0,33.6,11.5,21.8,0.529,1.4,3.6,0.388,10.2,18.3,0.556,0.561,10.2,11.6,0.883,2.4,8.6,11.0,5.6,1.2,1.7,3.8,2.9,34.7
1,Luka Dončić,70.0,70.0,37.5,11.5,23.6,0.487,4.1,10.6,0.382,7.4,13.0,0.573,0.573,6.8,8.7,0.786,0.8,8.4,9.2,9.8,1.4,0.5,4.0,2.1,33.9
2,Giannis Antetokounmpo,73.0,73.0,35.2,11.5,18.8,0.611,0.5,1.7,0.274,11.0,17.1,0.645,0.624,7.0,10.7,0.657,2.7,8.8,11.5,6.5,1.2,1.1,3.4,2.9,30.4
3,Shai Gilgeous-Alexander,75.0,75.0,34.0,10.6,19.8,0.535,1.3,3.6,0.353,9.3,16.2,0.576,0.567,7.6,8.7,0.874,0.9,4.7,5.5,6.2,2.0,0.9,2.2,2.5,30.1
4,Jalen Brunson,77.0,77.0,35.4,10.3,21.4,0.479,2.7,6.8,0.401,7.5,14.6,0.516,0.543,5.5,6.5,0.847,0.6,3.1,3.6,6.7,0.9,0.2,2.4,1.9,28.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,Danny Green,2.0,0.0,9.0,0.0,1.0,0.000,0.0,0.5,0.000,0.0,0.5,0.000,0.000,0.0,0.0,0.000,0.0,1.0,1.0,0.5,0.5,0.0,0.0,0.5,0.0
568,Ron Harper Jr.,1.0,0.0,4.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0
569,Justin Jackson,2.0,0.0,0.5,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
570,Dmytro Skapintsev,2.0,0.0,1.0,0.0,0.5,0.000,0.0,0.0,0.000,0.0,0.5,0.000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
571,Javonte Smart,1.0,0.0,1.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [224]:
advanced_ = advanced.drop(['Rk', 'Age', 'Team', 'Pos', 'Awards'], axis=1).\
                    drop_duplicates(subset=['Player'], keep='first', ignore_index=True).\
                    fillna(0).iloc[:-1]
advanced_

,Player,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,DeMar DeRozan,79.0,79.0,2989.0,19.7,0.584,0.166,0.452,1.6,11.3,6.4,21.8,1.5,1.5,7.7,25.8,7.0,2.2,9.2,0.147,2.1,-0.3,1.8,2.8
1,Domantas Sabonis,82.0,82.0,2928.0,23.2,0.637,0.081,0.389,11.0,32.3,21.4,33.9,1.2,1.5,17.9,22.2,8.6,4.0,12.6,0.206,4.0,2.4,6.5,6.2
2,Coby White,79.0,78.0,2881.0,14.5,0.570,0.460,0.215,1.7,12.4,6.9,20.8,0.9,0.6,11.1,22.7,3.1,1.6,4.7,0.078,0.7,-1.3,-0.7,0.9
3,Mikal Bridges,82.0,82.0,2854.0,14.9,0.560,0.457,0.245,2.5,12.0,7.1,16.3,1.4,0.9,10.3,24.3,2.1,2.1,4.2,0.070,0.7,-1.0,-0.4,1.2
4,Paolo Banchero,80.0,80.0,2799.0,17.3,0.546,0.249,0.397,3.4,20.0,11.6,25.2,1.3,1.6,13.0,29.7,1.3,4.0,5.3,0.090,1.3,0.0,1.3,2.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,Malcolm Cazalon,1.0,0.0,3.0,0.0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.012,-6.0,-3.2,-9.1,0.0
568,Jalen Crutcher,1.0,0.0,3.0,-12.6,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.5,0.0,0.0,0.0,-0.334,-18.5,-7.8,-26.2,0.0
569,Dmytro Skapintsev,2.0,0.0,2.0,-19.3,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.6,0.0,0.0,0.0,-0.483,-16.0,-9.8,-25.9,0.0
570,Justin Jackson,2.0,0.0,1.0,0.0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.031,-6.3,-1.2,-7.5,0.0
571,Javonte Smart,1.0,0.0,1.0,0.0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.005,-6.2,-2.1,-8.3,0.0

In [254]:
f = pd.merge(totals_, per_game_, how='outer')
f = pd.merge(f, advanced_, how='outer')
f = pd.merge(f, mvp_, how='outer')
f['Year'] = 2024
f

,Player,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,MPPG,FGPG,FGAPG,3PPG,3PAPG,2PPG,2PAPG,FTPG,FTAPG,ORBPG,DRBPG,TRBPG,ASTPG,STLPG,BLKPG,TOVPG,PFPG,PTSPG,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Share,Year
0,Luka Dončić,70.0,70.0,2624.0,804.0,1652.0,0.487,284.0,744.0,0.382,520.0,908.0,0.573,0.573,478.0,608.0,0.786,59.0,588.0,647.0,686.0,99.0,38.0,282.0,149.0,2370.0,21.0,37.5,11.5,23.6,4.1,10.6,7.4,13.0,6.8,8.7,0.8,8.4,9.2,9.8,1.4,0.5,4.0,2.1,33.9,28.1,0.617,0.450,0.368,2.5,24.4,13.5,44.3,1.8,1.3,12.8,36.0,8.5,3.5,12.0,0.220,8.3,1.7,9.9,8.0,0.572,2024
1,Shai Gilgeous-Alexander,75.0,75.0,2553.0,796.0,1487.0,0.535,95.0,269.0,0.353,701.0,1218.0,0.576,0.567,567.0,649.0,0.874,65.0,350.0,415.0,465.0,150.0,67.0,162.0,184.0,2254.0,0.0,34.0,10.6,19.8,1.3,3.6,9.3,16.2,7.6,8.7,0.9,4.7,5.5,6.2,2.0,0.9,2.2,2.5,30.1,29.3,0.636,0.181,0.436,3.0,14.7,9.1,29.8,2.8,2.4,8.4,32.8,10.5,4.2,14.6,0.275,6.7,2.3,9.0,7.1,0.646,2024
2,Giannis Antetokounmpo,73.0,73.0,2567.0,837.0,1369.0,0.611,34.0,124.0,0.274,803.0,1245.0,0.645,0.624,514.0,782.0,0.657,196.0,645.0,841.0,476.0,87.0,79.0,250.0,210.0,2222.0,10.0,35.2,11.5,18.8,0.5,1.7,11.0,17.1,7.0,10.7,2.7,8.8,11.5,6.5,1.2,1.1,3.4,2.9,30.4,29.9,0.649,0.091,0.571,8.6,27.0,17.9,32.7,1.6,2.6,12.7,33.0,9.5,3.7,13.2,0.246,6.7,2.4,9.0,7.2,0.194,2024
3,Jalen Brunson,77.0,77.0,2726.0,790.0,1648.0,0.479,211.0,526.0,0.401,579.0,1122.0,0.516,0.543,421.0,497.0,0.847,43.0,235.0,278.0,519.0,70.0,13.0,186.0,144.0,2212.0,0.0,35.4,10.3,21.4,2.7,6.8,7.5,14.6,5.5,6.5,0.6,3.1,3.6,6.7,0.9,0.2,2.4,1.9,28.7,23.4,0.592,0.319,0.302,1.8,9.7,5.7,33.5,1.3,0.4,9.1,32.5,8.8,2.4,11.2,0.198,6.3,-0.4,5.8,5.4,0.143,2024
4,Nikola Jokić,79.0,79.0,2737.0,822.0,1411.0,0.583,83.0,231.0,0.359,739.0,1180.0,0.626,0.612,358.0,438.0,0.817,223.0,753.0,976.0,708.0,108.0,68.0,237.0,194.0,2085.0,25.0,34.6,10.4,17.9,1.1,2.9,9.4,14.9,4.5,5.5,2.8,9.5,12.4,9.0,1.4,0.9,3.0,2.5,26.4,31.0,0.650,0.164,0.310,9.3,29.6,19.8,42.0,2.0,2.1,12.9,29.3,12.0,5.1,17.0,0.299,9.0,4.2,13.2,10.6,0.935,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,Danny Green,2.0,0.0,18.0,0.0,2.0,0.000,0.0,1.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,0.000,0.0,2.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,9.0,0.0,1.0,0.0,0.5,0.0,0.5,0.0,0.0,0.0,1.0,1.0,0.5,0.5,0.0,0.0,0.5,0.0,0.7,0.000,0.500,0.000,0.0,12.5,6.1,6.5,2.7,0.0,0.0,4.8,0.0,0.0,0.0,-0.035,-7.4,0.8,-6.6,0.0,NaN,2024
568,Ron Harper Jr.,1.0,0.0,4.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.0,28.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.087,-11.7,2.8,-8.8,0.0,NaN,2024
569,Justin Jackson,2.0,0.0,1.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.031,-6.3,-1.2,-7.5,0.0,NaN,2024
570,Dmytro Skapintsev,2.0,0.0,2.0,0.0,1.0,0.000,0.0,0.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.5,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-19.3,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.6,0.0,0.0,0.0,-0.483,-16.0,-9.8,-25.9,0.0,NaN,2024
571,Javonte Smart,1.0,0.0,1.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.005,-6.2,-2.1,-8.3,0.0,NaN,2024

In [276]:
df = pd.DataFrame()
if df.empty:
    df = f
else:
    df = pd.concat([df, f])

0                  Luka Dončić
1      Shai Gilgeous-Alexander
2        Giannis Antetokounmpo
3                Jalen Brunson
4                 Nikola Jokić
                ...
567                Danny Green
568             Ron Harper Jr.
569             Justin Jackson
570          Dmytro Skapintsev
571              Javonte Smart
Name: Player, Length: 572, dtype: object