In [50]:
import requests
import pandas as pd
import html5lib

url1 = 'https://www.basketball-reference.com/leagues/NBA_2022_totals.html'
total = pd.read_html(url1, header=0, attrs={'id':'totals_stats'})[0]

url2 = 'https://www.basketball-reference.com/awards/awards_2022.html'
mvp = pd.read_html(url2, header=1, attrs={'id':'mvp'})[0]

url3 = 'https://www.basketball-reference.com/leagues/NBA_2022_advanced.html'
advanced = pd.read_html(url3, header=0, attrs={'id':'advanced'})[0]

In [110]:
total_ = total.drop(['Rk', 'Age', 'Team', 'Pos', 'Awards'], axis=1).iloc[:-1]
total_ = total_.drop_duplicates(subset=['Player'], keep='first', ignore_index=True)
total_

,Player,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl
0,Trae Young,76.0,76.0,2652.0,711.0,1544.0,0.460,233.0,610.0,0.382,...,50.0,234.0,284.0,737.0,72.0,7.0,303.0,128.0,2155.0,0.0
1,DeMar DeRozan,76.0,76.0,2743.0,774.0,1535.0,0.504,50.0,142.0,0.352,...,56.0,336.0,392.0,374.0,68.0,24.0,181.0,178.0,2118.0,0.0
2,Joel Embiid,68.0,68.0,2297.0,666.0,1334.0,0.499,93.0,251.0,0.371,...,146.0,650.0,796.0,284.0,77.0,99.0,214.0,181.0,2079.0,2.0
3,Jayson Tatum,76.0,76.0,2731.0,708.0,1564.0,0.453,230.0,651.0,0.353,...,85.0,524.0,609.0,334.0,75.0,49.0,217.0,174.0,2046.0,0.0
4,Nikola Jokić,74.0,74.0,2476.0,764.0,1311.0,0.583,97.0,288.0,0.337,...,206.0,813.0,1019.0,584.0,109.0,63.0,281.0,191.0,2004.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Jaysean Paige,1.0,0.0,7.0,0.0,3.0,0.000,0.0,2.0,0.000,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0
601,Trayvon Palmer,1.0,0.0,17.0,0.0,1.0,0.000,0.0,0.0,NaN,...,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0
602,Emanuel Terry,3.0,0.0,18.0,0.0,5.0,0.000,0.0,0.0,NaN,...,8.0,7.0,15.0,2.0,1.0,0.0,5.0,4.0,0.0,0.0
603,Jon Teske,3.0,0.0,8.0,0.0,1.0,0.000,0.0,0.0,NaN,...,0.0,2.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
604,M.J. Walker,2.0,0.0,8.0,0.0,4.0,0.000,0.0,2.0,0.000,...,0.0,1.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0

In [76]:
mvp_ = mvp.drop(['Rank', 'Age', 'Tm'], axis=1)
mvp_

,Player,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,Nikola Jokić,65,875,1000,0.875,74,33.5,27.1,13.8,7.9,1.5,0.9,0.583,0.337,0.810,15.2,0.296
1,Joel Embiid,26,706,1000,0.706,68,33.8,30.6,11.7,4.2,1.1,1.5,0.499,0.371,0.814,12.0,0.252
2,Giannis Antetokounmpo,9,595,1000,0.595,67,32.9,29.9,11.6,5.8,1.1,1.4,0.553,0.293,0.722,12.9,0.281
3,Devin Booker,0,216,1000,0.216,68,34.5,26.8,5.0,4.8,1.1,0.4,0.466,0.383,0.868,7.6,0.156
4,Luka Dončić,0,146,1000,0.146,65,35.4,28.4,9.1,8.7,1.2,0.6,0.457,0.353,0.744,7.6,0.159
5,Jayson Tatum,0,43,1000,0.043,76,35.9,26.9,8.0,4.4,1.0,0.6,0.453,0.353,0.853,9.6,0.169
6,Ja Morant,0,10,1000,0.010,57,33.1,27.4,5.7,6.7,1.2,0.4,0.493,0.344,0.761,6.7,0.171
7,Stephen Curry,0,4,1000,0.004,64,34.5,25.5,5.2,6.3,1.3,0.4,0.437,0.380,0.923,8.0,0.173
8,Chris Paul,0,2,1000,0.002,65,32.9,14.7,4.4,10.8,1.9,0.3,0.493,0.317,0.837,9.4,0.210
9,DeMar DeRozan,0,1,1000,0.001,76,36.1,27.9,5.2,4.9,0.9,0.3,0.504,0.352,0.877,8.8,0.154
10,Kevin Durant,0,1,1000,0.001,55,37.2,29.9,7.4,6.4,0.9,0.9,0.518,0.383,0.910,8.4,0.198
11,LeBron James,0,1,1000,0.001,56,37.2,30.3,8.2,6.2,1.3,1.1,0.524,0.359,0.756,7.5,0.172

In [109]:
advanced_ = advanced.drop(['Rk', 'Age', 'Team', 'Pos', 'Awards'], axis=1).iloc[:-1].drop_duplicates(subset=['Player'], keep='first', ignore_index=True)
advanced_

,Player,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,Mikal Bridges,82.0,82.0,2854.0,14.4,0.627,0.364,0.183,2.9,10.0,...,6.8,15.0,5.2,3.7,8.9,0.150,0.5,1.1,1.6,2.6
1,Miles Bridges,80.0,80.0,2837.0,17.9,0.593,0.383,0.274,3.3,17.8,...,9.9,22.6,5.0,2.3,7.2,0.123,1.8,-0.3,1.5,2.5
2,DeMar DeRozan,76.0,76.0,2743.0,23.1,0.590,0.093,0.386,2.3,13.7,...,9.2,31.8,7.0,1.8,8.8,0.154,3.4,-0.9,2.5,3.1
3,Jayson Tatum,76.0,76.0,2731.0,21.8,0.578,0.416,0.300,3.5,20.2,...,10.9,32.1,5.0,4.6,9.6,0.169,4.3,0.6,5.0,4.8
4,Saddiq Bey,82.0,82.0,2704.0,14.0,0.529,0.537,0.224,4.1,14.1,...,7.1,21.3,2.4,1.6,4.0,0.071,0.9,-1.2,-0.3,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Matt Mooney,1.0,0.0,2.0,-20.0,0.000,1.000,0.000,0.0,0.0,...,50.0,43.8,-0.1,0.0,0.0,-0.915,-33.9,11.5,-22.3,0.0
601,Ahmad Caver,1.0,0.0,1.0,76.2,1.000,0.000,0.000,0.0,0.0,...,0.0,42.8,0.0,0.0,0.0,1.204,31.0,5.9,36.9,0.0
602,Sam Dekker,1.0,0.0,1.0,0.0,NaN,NaN,NaN,0.0,0.0,...,NaN,0.0,0.0,0.0,0.0,0.003,-6.2,-3.4,-9.6,0.0
603,DeJon Jarreau,1.0,0.0,1.0,0.0,NaN,NaN,NaN,0.0,0.0,...,NaN,0.0,0.0,0.0,0.0,-0.022,-6.5,-1.5,-8.0,0.0
604,Ade Murkey,1.0,0.0,1.0,0.0,NaN,NaN,NaN,0.0,0.0,...,NaN,0.0,0.0,0.0,0.0,-0.017,-7.4,-2.3,-9.7,0.0

In [123]:
combined = pd.merge(total_, advanced_, on='Player').fillna(0)
pd.set_option('display.max_columns', None)
combined

,Player,G_x,GS_x,MP_x,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,G_y,GS_y,MP_y,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,Trae Young,76.0,76.0,2652.0,711.0,1544.0,0.460,233.0,610.0,0.382,478.0,934.0,0.512,0.536,500.0,553.0,0.904,50.0,234.0,284.0,737.0,72.0,7.0,303.0,128.0,2155.0,0.0,76.0,76.0,2652.0,25.4,0.603,0.395,0.358,2.1,9.6,5.9,46.7,1.3,0.2,14.5,34.4,9.0,1.0,10.0,0.181,7.1,-2.0,5.2,4.8
1,DeMar DeRozan,76.0,76.0,2743.0,774.0,1535.0,0.504,50.0,142.0,0.352,724.0,1393.0,0.520,0.521,520.0,593.0,0.877,56.0,336.0,392.0,374.0,68.0,24.0,181.0,178.0,2118.0,0.0,76.0,76.0,2743.0,23.1,0.590,0.093,0.386,2.3,13.7,8.0,23.3,1.2,0.8,9.2,31.8,7.0,1.8,8.8,0.154,3.4,-0.9,2.5,3.1
2,Joel Embiid,68.0,68.0,2297.0,666.0,1334.0,0.499,93.0,251.0,0.371,573.0,1083.0,0.529,0.534,654.0,803.0,0.814,146.0,650.0,796.0,284.0,77.0,99.0,214.0,181.0,2079.0,2.0,68.0,68.0,2297.0,31.2,0.616,0.188,0.602,7.2,31.1,19.4,23.5,1.7,3.9,11.3,37.2,7.9,4.1,12.0,0.252,7.2,2.0,9.2,6.5
3,Jayson Tatum,76.0,76.0,2731.0,708.0,1564.0,0.453,230.0,651.0,0.353,478.0,913.0,0.524,0.526,400.0,469.0,0.853,85.0,524.0,609.0,334.0,75.0,49.0,217.0,174.0,2046.0,0.0,76.0,76.0,2731.0,21.8,0.578,0.416,0.300,3.5,20.2,12.1,21.1,1.4,1.6,10.9,32.1,5.0,4.6,9.6,0.169,4.3,0.6,5.0,4.8
4,Nikola Jokić,74.0,74.0,2476.0,764.0,1311.0,0.583,97.0,288.0,0.337,667.0,1023.0,0.652,0.620,379.0,468.0,0.810,206.0,813.0,1019.0,584.0,109.0,63.0,281.0,191.0,2004.0,19.0,74.0,74.0,2476.0,32.8,0.661,0.220,0.357,9.6,35.5,23.0,42.6,2.2,2.3,15.6,31.9,10.8,4.5,15.2,0.296,9.2,4.5,13.7,9.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Jaysean Paige,1.0,0.0,7.0,0.0,3.0,0.000,0.0,2.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,0.000,0.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,7.0,-22.2,0.000,0.667,0.000,0.0,16.3,7.7,18.1,0.0,0.0,25.0,24.5,-0.1,0.0,-0.1,-0.574,-25.0,-6.5,-31.5,0.0
601,Trayvon Palmer,1.0,0.0,17.0,0.0,1.0,0.000,0.0,0.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,0.000,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,17.0,-5.7,0.000,0.000,0.000,0.0,13.4,6.4,0.0,0.0,0.0,50.0,5.0,-0.1,0.0,0.0,-0.133,-13.1,-1.8,-15.0,-0.1
602,Emanuel Terry,3.0,0.0,18.0,0.0,5.0,0.000,0.0,0.0,0.000,0.0,5.0,0.000,0.000,0.0,0.0,0.000,8.0,7.0,15.0,2.0,1.0,0.0,5.0,4.0,0.0,0.0,3.0,0.0,18.0,-0.1,0.000,0.000,0.000,48.9,40.6,44.7,12.2,2.7,0.0,50.0,23.9,-0.1,0.0,-0.1,-0.256,-13.0,-5.3,-18.3,-0.1
603,Jon Teske,3.0,0.0,8.0,0.0,1.0,0.000,0.0,0.0,0.000,0.0,1.0,0.000,0.000,0.0,2.0,0.000,0.0,2.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,8.0,1.5,0.000,0.000,2.000,0.0,26.8,13.1,13.8,6.0,0.0,0.0,9.6,0.0,0.0,0.0,-0.080,-8.5,3.7,-4.8,0.0
604,M.J. Walker,2.0,0.0,8.0,0.0,4.0,0.000,0.0,2.0,0.000,0.0,2.0,0.000,0.000,0.0,0.0,0.000,0.0,1.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,8.0,-3.3,0.000,0.500,0.000,0.0,13.1,6.7,13.8,12.0,0.0,0.0,21.5,-0.1,0.0,0.0,-0.276,-15.8,6.2,-9.6,0.0

In [128]:
combined2 = pd.merge(combined, mvp_, how='left',on='Player')
combined2

,Player,G_x,GS_x,MP_x,FG,FGA,FG%_x,3P,3PA,3P%_x,2P,2PA,2P%,eFG%,FT,FTA,FT%_x,ORB,DRB,TRB_x,AST_x,STL_x,BLK_x,TOV,PF,PTS_x,Trp-Dbl,G_y,GS_y,MP_y,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,OWS,DWS,WS_x,WS/48_x,OBPM,DBPM,BPM,VORP,First,Pts Won,Pts Max,Share,G,MP,PTS_y,TRB_y,AST_y,STL_y,BLK_y,FG%_y,3P%_y,FT%_y,WS_y,WS/48_y
0,Trae Young,76.0,76.0,2652.0,711.0,1544.0,0.460,233.0,610.0,0.382,478.0,934.0,0.512,0.536,500.0,553.0,0.904,50.0,234.0,284.0,737.0,72.0,7.0,303.0,128.0,2155.0,0.0,76.0,76.0,2652.0,25.4,0.603,0.395,0.358,2.1,9.6,5.9,46.7,1.3,0.2,14.5,34.4,9.0,1.0,10.0,0.181,7.1,-2.0,5.2,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DeMar DeRozan,76.0,76.0,2743.0,774.0,1535.0,0.504,50.0,142.0,0.352,724.0,1393.0,0.520,0.521,520.0,593.0,0.877,56.0,336.0,392.0,374.0,68.0,24.0,181.0,178.0,2118.0,0.0,76.0,76.0,2743.0,23.1,0.590,0.093,0.386,2.3,13.7,8.0,23.3,1.2,0.8,9.2,31.8,7.0,1.8,8.8,0.154,3.4,-0.9,2.5,3.1,0.0,1.0,1000.0,0.001,76.0,36.1,27.9,5.2,4.9,0.9,0.3,0.504,0.352,0.877,8.8,0.154
2,Joel Embiid,68.0,68.0,2297.0,666.0,1334.0,0.499,93.0,251.0,0.371,573.0,1083.0,0.529,0.534,654.0,803.0,0.814,146.0,650.0,796.0,284.0,77.0,99.0,214.0,181.0,2079.0,2.0,68.0,68.0,2297.0,31.2,0.616,0.188,0.602,7.2,31.1,19.4,23.5,1.7,3.9,11.3,37.2,7.9,4.1,12.0,0.252,7.2,2.0,9.2,6.5,26.0,706.0,1000.0,0.706,68.0,33.8,30.6,11.7,4.2,1.1,1.5,0.499,0.371,0.814,12.0,0.252
3,Jayson Tatum,76.0,76.0,2731.0,708.0,1564.0,0.453,230.0,651.0,0.353,478.0,913.0,0.524,0.526,400.0,469.0,0.853,85.0,524.0,609.0,334.0,75.0,49.0,217.0,174.0,2046.0,0.0,76.0,76.0,2731.0,21.8,0.578,0.416,0.300,3.5,20.2,12.1,21.1,1.4,1.6,10.9,32.1,5.0,4.6,9.6,0.169,4.3,0.6,5.0,4.8,0.0,43.0,1000.0,0.043,76.0,35.9,26.9,8.0,4.4,1.0,0.6,0.453,0.353,0.853,9.6,0.169
4,Nikola Jokić,74.0,74.0,2476.0,764.0,1311.0,0.583,97.0,288.0,0.337,667.0,1023.0,0.652,0.620,379.0,468.0,0.810,206.0,813.0,1019.0,584.0,109.0,63.0,281.0,191.0,2004.0,19.0,74.0,74.0,2476.0,32.8,0.661,0.220,0.357,9.6,35.5,23.0,42.6,2.2,2.3,15.6,31.9,10.8,4.5,15.2,0.296,9.2,4.5,13.7,9.8,65.0,875.0,1000.0,0.875,74.0,33.5,27.1,13.8,7.9,1.5,0.9,0.583,0.337,0.810,15.2,0.296
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Jaysean Paige,1.0,0.0,7.0,0.0,3.0,0.000,0.0,2.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,0.000,0.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,7.0,-22.2,0.000,0.667,0.000,0.0,16.3,7.7,18.1,0.0,0.0,25.0,24.5,-0.1,0.0,-0.1,-0.574,-25.0,-6.5,-31.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
601,Trayvon Palmer,1.0,0.0,17.0,0.0,1.0,0.000,0.0,0.0,0.000,0.0,1.0,0.000,0.000,0.0,0.0,0.000,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,17.0,-5.7,0.000,0.000,0.000,0.0,13.4,6.4,0.0,0.0,0.0,50.0,5.0,-0.1,0.0,0.0,-0.133,-13.1,-1.8,-15.0,-0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
602,Emanuel Terry,3.0,0.0,18.0,0.0,5.0,0.000,0.0,0.0,0.000,0.0,5.0,0.000,0.000,0.0,0.0,0.000,8.0,7.0,15.0,2.0,1.0,0.0,5.0,4.0,0.0,0.0,3.0,0.0,18.0,-0.1,0.000,0.000,0.000,48.9,40.6,44.7,12.2,2.7,0.0,50.0,23.9,-0.1,0.0,-0.1,-0.256,-13.0,-5.3,-18.3,-0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
603,Jon Teske,3.0,0.0,8.0,0.0,1.0,0.000,0.0,0.0,0.000,0.0,1.0,0.000,0.000,0.0,2.0,0.000,0.0,2.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,8.0,1.5,0.000,0.000,2.000,0.0,26.8,13.1,13.8,6.0,0.0,0.0,9.6,0.0,0.0,0.0,-0.080,-8.5,3.7,-4.8,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
604,M.J. Walker,2.0,0.0,8.0,0.0,4.0,0.000,0.0,2.0,0.000,0.0,2.0,0.000,0.000,0.0,0.0,0.000,0.0,1.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,8.0,-3.3,0.000,0.500,0.000,0.0,13.1,6.7,13.8,12.0,0.0,0.0,21.5,-0.1,0.0,0.0,-0.276,-15.8,6.2,-9.6,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
import os
year = 2023
file_name = '{}.csv'
mvp.to_csv(os.path.join('mvp-data/',file_name.format(year)))

In [48]:
adjusted_df = df.drop_duplicates(subset='Player', keep='first')
adjusted_df.drop(['Rk', 'Age', 'Team', 'Pos', 'Awards'], axis=1)

,Player,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl
0,Trae Young,76.0,76.0,2652.0,711.0,1544.0,0.460,233.0,610.0,0.382,...,50.0,234.0,284.0,737.0,72.0,7.0,303.0,128.0,2155.0,0.0
1,DeMar DeRozan,76.0,76.0,2743.0,774.0,1535.0,0.504,50.0,142.0,0.352,...,56.0,336.0,392.0,374.0,68.0,24.0,181.0,178.0,2118.0,0.0
2,Joel Embiid,68.0,68.0,2297.0,666.0,1334.0,0.499,93.0,251.0,0.371,...,146.0,650.0,796.0,284.0,77.0,99.0,214.0,181.0,2079.0,2.0
3,Jayson Tatum,76.0,76.0,2731.0,708.0,1564.0,0.453,230.0,651.0,0.353,...,85.0,524.0,609.0,334.0,75.0,49.0,217.0,174.0,2046.0,0.0
4,Nikola Jokić,74.0,74.0,2476.0,764.0,1311.0,0.583,97.0,288.0,0.337,...,206.0,813.0,1019.0,584.0,109.0,63.0,281.0,191.0,2004.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808,Trayvon Palmer,1.0,0.0,17.0,0.0,1.0,0.000,0.0,0.0,NaN,...,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0
809,Emanuel Terry,3.0,0.0,18.0,0.0,5.0,0.000,0.0,0.0,NaN,...,8.0,7.0,15.0,2.0,1.0,0.0,5.0,4.0,0.0,0.0
810,Jon Teske,3.0,0.0,8.0,0.0,1.0,0.000,0.0,0.0,NaN,...,0.0,2.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
811,M.J. Walker,2.0,0.0,8.0,0.0,4.0,0.000,0.0,2.0,0.000,...,0.0,1.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0
812,League Average,NaN,NaN,NaN,NaN,NaN,0.461,NaN,NaN,0.354,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
import pandas as pd
ex = pd.DataFrame([[1, 2, 3, 4], [12, 13, 14, 15]], columns=['a', 'b', 'c', 'd'])
ex2 = pd.DataFrame([[1, 2, 5, 6, 7, 8, 9, 0]], columns=['a', 'b', 'e', 'f', 'g', 'h', 'i', 'j'])
final = ex.merge(ex2)
#final
final

   a  b  c  d  e  f  g  h  i  j
0  1  2  3  4  5  6  7  8  9  0

In [36]:
A = pd.DataFrame([[3, 1, 4, 1]], columns=['id', 'trial', 'trial', 'trial'])