In [2]:
import pandas as pd

#total = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2024_totals.html#totals_stats')[0]
#advanced = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2024_advanced.html#advanced')[0]
#mvp = pd.read_html('https://www.basketball-reference.com/awards/awards_2024.html#mvp')[0]
team = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2004.html#advanced-team')

In [3]:
display(total.columns)
display(advanced.columns)
display(mvp)
#display(team[0])

Index(['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Trp-Dbl', 'Awards'],
      dtype='object')

Index(['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'PER', 'TS%',
       '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%',
       'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP',
       'Awards'],
      dtype='object')

  Unnamed: 0_level_0       Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Rank                   Player                Age
0                  1             Nikola Jokić                 28
1                  2  Shai Gilgeous-Alexander                 25
2                  3              Luka Dončić                 24
3                  4    Giannis Antetokounmpo                 29
4                  5            Jalen Brunson                 27
5                  6             Jayson Tatum                 25
6                  7          Anthony Edwards                 22
7                  8         Domantas Sabonis                 27
8                  9             Kevin Durant                 35

  Unnamed: 3_level_0 Voting                        Unnamed: 8_level_0  \
                  Tm  First Pts Won Pts Max  Share                  G
0                DEN     79     926     990  0.935                 79
1                OKC     15     640     990  0.646                 75
2                DAL      4     566     990  0.572                 70
3                MIL      1     192     990  0.194                 73
4                NYK      0     142     990  0.143                 77
5                BOS      0      86     990  0.087                 74
6                MIN      0      18     990  0.018                 79
7                SAC      0       3     990  0.003                 82
8                PHO      0       1     990  0.001                 75

  Per Game                            Shooting               Advanced
        MP   PTS   TRB  AST  STL  BLK      FG%    3P%    FT%       WS  WS/48
0     34.6  26.4  12.4  9.0  1.4  0.9    0.583  0.359  0.817     17.0  0.299
1     34.0  30.1   5.5  6.2  2.0  0.9    0.535  0.353  0.874     14.6  0.275
2     37.5  33.9   9.2  9.8  1.4  0.5    0.487  0.382  0.786     12.0  0.220
3     35.2  30.4  11.5  6.5  1.2  1.1    0.611  0.274  0.657     13.2  0.246
4     35.4  28.7   3.6  6.7  0.9  0.2    0.479  0.401  0.847     11.2  0.198
5     35.7  26.9   8.1  4.9  1.0  0.6    0.471  0.376  0.833     10.4  0.189
6     35.1  25.9   5.4  5.1  1.3  0.5    0.461  0.357  0.836      7.5  0.130
7     35.7  19.4  13.7  8.2  0.9  0.6    0.594  0.379  0.704     12.6  0.206
8     37.2  27.1   6.6  5.0  0.9  1.2    0.523  0.413  0.856      8.3  0.142

In [4]:
east, west = team[0].copy(), team[1].copy()
east = east[east['Eastern Conference'].str.contains('Division') == False]
west = west[west['Western Conference'].str.contains('Division') == False]
east.rename(columns={'Eastern Conference':'Team'}, inplace=True) 
west.rename(columns={'Western Conference':'Team'}, inplace=True)
east['Seed'] = range(1, len(east) + 1)
west['Seed'] = range(1, len(east) + 1)
team_ = pd.concat([east, west], ignore_index=True)
team_['Team'] = team_['Team'].str.replace(r'\*','', regex=True)
display(team_)

                      Team   W   L   W/L%    GB   PS/G   PA/G    SRS  Seed
0           Boston Celtics  64  18  0.780     —  120.6  109.2  10.75     1
1          New York Knicks  50  32  0.610  14.0  112.8  108.2   4.36     2
2          Milwaukee Bucks  49  33  0.598  15.0  119.0  116.4   2.44     3
3      Cleveland Cavaliers  48  34  0.585  16.0  112.6  110.2   1.98     4
4            Orlando Magic  47  35  0.573  17.0  110.5  108.4   1.48     5
5           Indiana Pacers  47  35  0.573  17.0  123.3  120.2   2.75     6
6       Philadelphia 76ers  47  35  0.573  17.0  114.6  111.5   2.51     7
7               Miami Heat  46  36  0.561  18.0  110.1  108.4   1.10     8
8            Chicago Bulls  39  43  0.476  25.0  112.3  113.7  -1.77     9
9            Atlanta Hawks  36  46  0.439  28.0  118.3  120.5  -2.38    10
10           Brooklyn Nets  32  50  0.390  32.0  110.4  113.3  -3.02    11
11         Toronto Raptors  25  57  0.305  39.0  112.4  118.8  -6.45    12
12       Charlotte Hornets  21  61  0.256  43.0  106.6  116.8 -10.12    13
13      Washington Wizards  15  67  0.183  49.0  113.7  123.0  -9.29    14
14         Detroit Pistons  14  68  0.171  50.0  109.9  119.0  -9.06    15
15   Oklahoma City Thunder  57  25  0.695     —  120.1  112.7   7.36     1
16          Denver Nuggets  57  25  0.695     —  114.9  109.6   5.23     2
17  Minnesota Timberwolves  56  26  0.683   1.0  113.0  106.5   6.39     3
18    Los Angeles Clippers  51  31  0.622   6.0  115.6  112.3   3.41     4
19        Dallas Mavericks  50  32  0.610   7.0  117.9  115.6   2.30     5
20            Phoenix Suns  49  33  0.598   8.0  116.2  113.2   3.08     6
21    New Orleans Pelicans  49  33  0.598   8.0  115.1  110.7   4.46     7
22      Los Angeles Lakers  47  35  0.573  10.0  118.0  117.4   1.07     8
23        Sacramento Kings  46  36  0.561  11.0  116.6  114.8   2.29     9
24   Golden State Warriors  46  36  0.561  11.0  117.8  115.2   2.77    10
25         Houston Rockets  41  41  0.500  16.0  114.3  113.2   1.24    11
26               Utah Jazz  31  51  0.378  26.0  115.7  120.5  -4.22    12
27       Memphis Grizzlies  27  55  0.329  30.0  105.8  112.8  -6.57    13
28       San Antonio Spurs  22  60  0.268  35.0  112.1  118.6  -5.80    14
29  Portland Trail Blazers  21  61  0.256  36.0  106.4  115.4  -8.29    15

In [3]:
def process_team(team):
    east, west = team[0].copy(), team[1].copy()

    nba_teams = {
    "Atlanta Hawks": "ATL",
    "Boston Celtics": "BOS",
    "Brooklyn Nets": "BRK",  # Sometimes "BKN"
    "Chicago Bulls": "CHI",
    "Charlotte Hornets": "CHO",  # Sometimes "CHA"
    "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL",
    "Denver Nuggets": "DEN",
    "Detroit Pistons": "DET",
    "Golden State Warriors": "GSW",
    "Houston Rockets": "HOU",
    "Indiana Pacers": "IND",
    "Los Angeles Clippers": "LAC",
    "Los Angeles Lakers": "LAL",
    "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA",
    "Milwaukee Bucks": "MIL",
    "Minnesota Timberwolves": "MIN",
    "New Orleans Pelicans": "NOP",
    "New York Knicks": "NYK",
    "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL",
    "Philadelphia 76ers": "PHI",
    "Phoenix Suns": "PHO",
    "Portland Trail Blazers": "POR",
    "Sacramento Kings": "SAC",
    "San Antonio Spurs": "SAS",
    "Toronto Raptors": "TOR",
    "Utah Jazz": "UTA",
    "Washington Wizards": "WAS",

    # Historical/renamed teams since 2004:
    "Seattle SuperSonics": "SEA",
    "New Jersey Nets": "NJN",
    "Charlotte Bobcats": "CHA",
    "New Orleans Hornets": "NOH",  # Also seen as "NOK" during Katrina years
    "New Orleans/Oklahoma City Hornets": "NOK"
    }
    
    east = east[east['Eastern Conference'].str.contains('Division') == False]
    west = west[west['Western Conference'].str.contains('Division') == False]
    east.rename(columns={'Eastern Conference':'Team'}, inplace=True) 
    west.rename(columns={'Western Conference':'Team'}, inplace=True)
    east = east.sort_values(by='W/L%', ascending=False)
    west = west.sort_values(by='W/L%', ascending=False)
    east['Seed'] = range(1, len(east) + 1)
    west['Seed'] = range(1, len(west) + 1)
    df = pd.concat([east, west], ignore_index=True)
    df['Team'] = df['Team'].str.replace(r'\*','', regex=True)
    df['Team'] = df['Team'].map(nba_teams)
    return df.loc[:, ['Team', 'W/L%', 'Seed']]

team_ = process_team(team)
team_

   Team  W/L%  Seed
0   IND  .744     1
1   DET  .659     2
2   NJN  .573     3
3   MIA  .512     4
4   NOH  .500     5
5   MIL  .500     6
6   NYK  .476     7
7   BOS  .439     8
8   CLE  .427     9
9   PHI  .402    10
10  TOR  .402    11
11  ATL  .341    12
12  WAS  .305    13
13  CHI  .280    14
14  ORL  .256    15
15  MIN  .707     1
16  SAS  .695     2
17  LAL  .683     3
18  SAC  .671     4
19  DAL  .634     5
20  MEM  .610     6
21  HOU  .549     7
22  DEN  .524     8
23  UTA  .512     9
24  POR  .500    10
25  GSW  .451    11
26  SEA  .451    12
27  PHO  .354    13
28  LAC  .341    14

In [228]:
total_ = total.loc[:, ['Player','Team','G','GS', 'MP','FG%','3P%','2P%', 'eFG%']].iloc[:-1]
total_['MP'] = round(total_['MP']/total_['G'], 1)
advanced_ = advanced.loc[:,['Player', 'Team', 'PER', '3PAr', 'ORB%','DRB%','TRB%','AST%','STL%','BLK%','TOV%','USG%','OWS','DWS','WS','WS/48']].iloc[:-1]
stats = pd.merge(total_, advanced_, how='outer')
stats.head(50)

,Player,Team,G,GS,MP,FG%,3P%,2P%,eFG%,PER,3PAr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,OWS,DWS,WS,WS/48
0,A.J. Green,MIL,56.0,0.0,11.0,0.423,0.408,0.519,0.599,10.5,0.862,1.6,9.6,5.7,6.4,0.7,0.6,5.5,15.2,0.7,0.3,1.1,0.084
1,A.J. Lawson,DAL,42.0,0.0,7.4,0.446,0.260,0.577,0.500,11.2,0.413,4.9,12.6,8.8,8.9,1.5,0.8,9.6,20.0,0.0,0.3,0.2,0.036
2,AJ Griffin,ATL,20.0,0.0,8.6,0.290,0.256,0.348,0.371,1.2,0.629,1.2,10.6,5.7,3.7,0.3,1.1,11.3,17.3,-0.4,0.0,-0.4,-0.120
3,Aaron Gordon,DEN,73.0,73.0,31.5,0.556,0.290,0.619,0.584,16.8,0.193,8.6,13.9,11.4,15.2,1.2,1.7,11.2,17.8,4.5,2.6,7.1,0.148
4,Aaron Holiday,HOU,78.0,1.0,16.3,0.446,0.387,0.510,0.547,11.5,0.520,1.9,8.5,5.2,15.4,1.6,0.4,10.6,16.7,1.3,1.2,2.5,0.094
5,Aaron Nesmith,IND,72.0,47.0,27.7,0.496,0.419,0.581,0.606,12.8,0.526,3.6,12.0,7.8,6.6,1.5,2.0,8.4,16.0,2.8,1.3,4.1,0.098
6,Aaron Wiggins,OKC,78.0,4.0,15.7,0.562,0.492,0.598,0.645,15.6,0.334,5.7,11.0,8.4,9.3,2.2,1.4,12.1,16.4,2.1,1.6,3.7,0.144
7,Adam Flagler,OKC,2.0,0.0,7.0,0.143,0.167,0.000,0.214,0.6,0.857,0.0,0.0,0.0,33.6,0.0,0.0,0.0,21.7,0.0,0.0,0.0,-0.159
8,Adama Sanogo,CHI,9.0,0.0,7.3,0.519,NaN,0.519,0.519,21.9,0.000,31.6,29.4,30.5,0.0,0.8,0.0,13.4,24.8,0.1,0.1,0.2,0.133
9,Admiral Schofield,ORL,23.0,0.0,3.7,0.385,0.375,0.400,0.500,6.0,0.615,4.2,19.7,11.9,11.6,0.6,0.0,15.7,16.6,-0.1,0.1,0.0,0.006
10,Al Horford,BOS,65.0,33.0,26.8,0.511,0.419,0.658,0.640,15.0,0.616,5.3,19.7,12.8,12.3,1.1,3.1,10.0,12.0,3.5,2.7,6.2,0.172
11,Alec Burks,2TM,66.0,1.0,18.4,0.369,0.376,0.360,0.478,12.9,0.580,2.2,11.8,6.9,10.7,1.1,0.9,7.0,24.4,0.7,0.7,1.4,0.054
12,Alec Burks,DET,43.0,0.0,21.0,0.394,0.401,0.384,0.516,15.1,0.608,1.9,11.8,6.8,11.2,1.1,1.0,6.4,23.5,1.3,0.4,1.7,0.092
13,Alec Burks,NYK,23.0,1.0,13.5,0.307,0.301,0.313,0.383,6.5,0.509,2.9,11.6,7.2,9.2,1.1,0.3,8.3,26.9,-0.6,0.3,-0.4,-0.055
14,Aleksej Pokusevski,2TM,28.0,0.0,14.5,0.405,0.327,0.470,0.479,12.7,0.455,4.6,20.4,12.3,12.0,1.8,3.0,12.0,17.2,0.0,0.4,0.4,0.050
15,Aleksej Pokusevski,CHO,18.0,0.0,19.2,0.429,0.364,0.475,0.505,14.5,0.419,4.7,21.5,12.9,12.4,2.0,3.2,11.7,17.6,0.2,0.3,0.5,0.070
16,Aleksej Pokusevski,OKC,10.0,0.0,6.0,0.250,0.182,0.400,0.313,2.5,0.688,3.9,14.3,9.3,9.7,0.8,1.5,14.5,15.0,-0.1,0.1,-0.1,-0.063
17,Alex Caruso,CHI,71.0,57.0,28.7,0.468,0.408,0.563,0.593,14.5,0.616,3.3,11.8,7.5,16.4,2.9,3.5,14.9,14.7,2.3,2.6,4.9,0.115
18,Alex Fudge,2TM,6.0,0.0,6.7,0.400,0.200,0.500,0.433,9.8,0.333,11.3,2.7,6.9,0.0,3.6,0.0,11.2,19.2,0.0,0.0,0.0,-0.007
19,Alex Fudge,DAL,2.0,0.0,13.0,0.556,0.333,0.667,0.611,16.2,0.333,8.4,4.2,6.3,0.0,5.5,0.0,10.0,16.5,0.0,0.0,0.1,0.108
20,Alex Fudge,LAL,4.0,0.0,3.5,0.167,0.000,0.250,0.167,-1.9,0.333,16.7,0.0,7.9,0.0,0.0,0.0,12.7,24.3,-0.1,0.0,-0.1,-0.222
21,Alex Len,SAC,48.0,0.0,9.2,0.617,0.000,0.641,0.617,14.7,0.037,11.3,21.2,16.1,14.4,1.2,6.8,22.0,11.8,0.6,0.7,1.3,0.138
22,Alondes Williams,MIA,7.0,0.0,2.3,0.250,0.000,0.500,0.250,-7.9,0.500,0.0,7.1,3.5,0.0,0.0,6.1,19.2,29.1,-0.1,0.0,-0.1,-0.357
23,Alperen Şengün,HOU,63.0,63.0,32.5,0.537,0.297,0.567,0.553,22.0,0.113,9.5,21.5,15.4,25.2,1.8,2.1,12.5,27.0,3.8,3.1,6.9,0.163
24,Amari Bailey,CHO,10.0,0.0,6.5,0.333,0.125,0.438,0.354,9.7,0.333,10.1,5.3,7.8,15.2,2.3,0.0,12.9,21.1,-0.1,0.0,-0.1,-0.044
25,Amen Thompson,HOU,62.0,23.0,22.4,0.536,0.138,0.595,0.545,18.2,0.130,11.3,20.4,15.8,17.0,2.7,2.5,14.9,18.5,1.9,2.4,4.3,0.149
26,Amir Coffey,LAC,70.0,13.0,20.9,0.472,0.380,0.571,0.571,10.0,0.523,2.3,8.9,5.7,6.8,1.4,0.9,7.9,12.5,1.6,1.0,2.6,0.084
27,Andre Drummond,CHI,79.0,10.0,17.1,0.556,0.000,0.560,0.556,23.0,0.006,21.5,37.4,29.3,4.1,2.7,3.6,12.3,21.3,2.3,2.6,4.9,0.175
28,Andre Jackson Jr.,MIL,57.0,8.0,10.0,0.500,0.370,0.611,0.585,8.5,0.460,8.4,13.1,10.8,10.8,1.3,0.9,21.1,10.0,0.5,0.5,1.0,0.081
29,Andrew Funk,CHI,5.0,0.0,2.6,0.000,0.000,0.000,0.000,-5.0,0.750,0.0,0.0,0.0,0.0,3.8,7.9,0.0,13.5,-0.1,0.0,-0.1,-0.252
30,Andrew Nembhard,IND,68.0,47.0,25.0,0.498,0.357,0.567,0.557,11.3,0.328,2.4,7.0,4.7,20.0,1.8,0.3,15.6,16.0,1.3,0.7,2.0,0.057
31,Andrew Wiggins,GSW,71.0,59.0,27.0,0.453,0.358,0.498,0.511,12.7,0.326,6.2,11.8,9.0,8.6,1.1,1.9,9.2,20.9,1.2,1.6,2.8,0.070
32,Anfernee Simons,POR,46.0,46.0,34.4,0.430,0.385,0.472,0.523,15.9,0.484,1.5,10.9,5.9,27.6,0.7,0.3,12.1,28.0,1.7,0.5,2.2,0.068
33,Anthony Black,ORL,69.0,33.0,16.9,0.466,0.394,0.510,0.540,8.4,0.381,3.3,10.8,7.0,10.6,1.5,1.7,16.6,12.7,0.1,1.5,1.6,0.067
34,Anthony Davis,LAL,76.0,76.0,35.5,0.556,0.271,0.582,0.567,25.8,0.083,10.4,28.3,19.8,15.5,1.6,5.7,9.5,26.7,7.2,4.7,11.8,0.210
35,Anthony Edwards,MIN,79.0,78.0,35.1,0.461,0.357,0.515,0.522,19.7,0.341,2.2,14.8,8.8,24.6,1.8,1.3,11.9,32.3,2.9,4.7,7.5,0.130
36,Anthony Gill,WAS,50.0,3.0,9.3,0.469,0.244,0.546,0.500,12.1,0.256,8.3,13.4,10.8,10.0,1.3,1.9,11.6,18.0,0.1,0.2,0.4,0.038
37,Armoni Brooks,BRK,10.0,0.0,10.4,0.326,0.344,0.286,0.446,8.3,0.696,7.2,11.9,9.5,6.9,0.5,0.9,6.0,20.8,-0.1,0.1,0.0,-0.018
38,Ashton Hagans,POR,19.0,1.0,16.6,0.408,0.320,0.457,0.465,8.5,0.352,4.7,11.7,8.0,23.7,1.7,2.6,27.7,14.6,-0.2,0.3,0.0,0.006
39,Ausar Thompson,DET,63.0,38.0,25.1,0.483,0.186,0.575,0.505,12.8,0.235,8.9,19.6,14.2,10.8,2.1,3.2,13.6,16.6,0.1,1.7,1.8,0.053
40,Austin Reaves,LAL,82.0,57.0,32.1,0.486,0.367,0.583,0.568,15.5,0.447,2.5,11.9,7.4,23.5,1.2,0.8,14.1,20.3,3.9,2.0,5.9,0.108
41,Ayo Dosunmu,CHI,76.0,37.0,29.1,0.501,0.403,0.568,0.583,13.4,0.410,2.7,8.3,5.5,15.6,1.5,1.7,11.9,17.2,2.6,1.5,4.1,0.089
42,Bam Adebayo,MIA,71.0,71.0,34.0,0.521,0.357,0.528,0.529,19.8,0.041,7.4,27.3,17.3,18.9,1.7,2.7,12.0,24.9,2.9,4.3,7.2,0.144
43,Ben Sheppard,IND,57.0,1.0,14.3,0.393,0.314,0.562,0.500,8.1,0.681,2.1,10.3,6.2,7.5,1.9,0.2,5.9,13.2,0.3,0.4,0.8,0.046
44,Ben Simmons,BRK,15.0,12.0,23.9,0.581,NaN,0.581,0.581,16.3,0.000,9.2,27.6,18.1,33.2,1.7,2.3,25.1,13.0,0.5,0.5,1.0,0.133
45,Bennedict Mathurin,IND,59.0,19.0,26.1,0.446,0.374,0.481,0.507,13.0,0.323,4.4,12.8,8.6,9.8,1.1,0.7,11.3,23.4,0.8,0.7,1.4,0.045
46,Bilal Coulibaly,WAS,63.0,15.0,27.2,0.435,0.346,0.502,0.509,8.9,0.428,3.4,12.8,8.0,8.2,1.6,2.3,15.1,14.2,-0.5,0.9,0.4,0.013
47,Bismack Biyombo,2TM,40.0,27.0,19.8,0.565,NaN,0.565,0.565,9.9,0.000,8.3,21.1,14.5,9.5,0.7,4.4,21.3,10.7,0.1,1.0,1.1,0.066
48,Bismack Biyombo,MEM,30.0,27.0,23.9,0.563,NaN,0.563,0.563,10.0,0.000,8.3,21.3,14.5,10.1,0.7,4.4,21.4,10.6,0.1,0.9,1.0,0.066
49,Bismack Biyombo,OKC,10.0,0.0,7.3,0.583,NaN,0.583,0.583,8.9,0.000,7.9,19.1,13.7,3.3,0.7,3.8,20.5,11.6,0.0,0.1,0.1,0.066

In [229]:
correct_teams = stats.drop_duplicates(subset=['Player'], keep='last', ignore_index=True)
correct_teams = correct_teams.loc[:,['Player', 'Team']]
stats_ = stats.drop_duplicates(subset=['Player'], keep='first', ignore_index=True)
final = pd.merge(stats_.drop(columns=('Team')), correct_teams, how='outer')
cols = list(final.columns)
cols.insert(1, cols.pop(cols.index("Team")))
final = final[cols]
final.head(50)

,Player,Team,G,GS,MP,FG%,3P%,2P%,eFG%,PER,3PAr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,OWS,DWS,WS,WS/48
0,A.J. Green,MIL,56.0,0.0,11.0,0.423,0.408,0.519,0.599,10.5,0.862,1.6,9.6,5.7,6.4,0.7,0.6,5.5,15.2,0.7,0.3,1.1,0.084
1,A.J. Lawson,DAL,42.0,0.0,7.4,0.446,0.260,0.577,0.500,11.2,0.413,4.9,12.6,8.8,8.9,1.5,0.8,9.6,20.0,0.0,0.3,0.2,0.036
2,AJ Griffin,ATL,20.0,0.0,8.6,0.290,0.256,0.348,0.371,1.2,0.629,1.2,10.6,5.7,3.7,0.3,1.1,11.3,17.3,-0.4,0.0,-0.4,-0.120
3,Aaron Gordon,DEN,73.0,73.0,31.5,0.556,0.290,0.619,0.584,16.8,0.193,8.6,13.9,11.4,15.2,1.2,1.7,11.2,17.8,4.5,2.6,7.1,0.148
4,Aaron Holiday,HOU,78.0,1.0,16.3,0.446,0.387,0.510,0.547,11.5,0.520,1.9,8.5,5.2,15.4,1.6,0.4,10.6,16.7,1.3,1.2,2.5,0.094
5,Aaron Nesmith,IND,72.0,47.0,27.7,0.496,0.419,0.581,0.606,12.8,0.526,3.6,12.0,7.8,6.6,1.5,2.0,8.4,16.0,2.8,1.3,4.1,0.098
6,Aaron Wiggins,OKC,78.0,4.0,15.7,0.562,0.492,0.598,0.645,15.6,0.334,5.7,11.0,8.4,9.3,2.2,1.4,12.1,16.4,2.1,1.6,3.7,0.144
7,Adam Flagler,OKC,2.0,0.0,7.0,0.143,0.167,0.000,0.214,0.6,0.857,0.0,0.0,0.0,33.6,0.0,0.0,0.0,21.7,0.0,0.0,0.0,-0.159
8,Adama Sanogo,CHI,9.0,0.0,7.3,0.519,NaN,0.519,0.519,21.9,0.000,31.6,29.4,30.5,0.0,0.8,0.0,13.4,24.8,0.1,0.1,0.2,0.133
9,Admiral Schofield,ORL,23.0,0.0,3.7,0.385,0.375,0.400,0.500,6.0,0.615,4.2,19.7,11.9,11.6,0.6,0.0,15.7,16.6,-0.1,0.1,0.0,0.006
10,Al Horford,BOS,65.0,33.0,26.8,0.511,0.419,0.658,0.640,15.0,0.616,5.3,19.7,12.8,12.3,1.1,3.1,10.0,12.0,3.5,2.7,6.2,0.172
11,Alec Burks,NYK,66.0,1.0,18.4,0.369,0.376,0.360,0.478,12.9,0.580,2.2,11.8,6.9,10.7,1.1,0.9,7.0,24.4,0.7,0.7,1.4,0.054
12,Aleksej Pokusevski,OKC,28.0,0.0,14.5,0.405,0.327,0.470,0.479,12.7,0.455,4.6,20.4,12.3,12.0,1.8,3.0,12.0,17.2,0.0,0.4,0.4,0.050
13,Alex Caruso,CHI,71.0,57.0,28.7,0.468,0.408,0.563,0.593,14.5,0.616,3.3,11.8,7.5,16.4,2.9,3.5,14.9,14.7,2.3,2.6,4.9,0.115
14,Alex Fudge,LAL,6.0,0.0,6.7,0.400,0.200,0.500,0.433,9.8,0.333,11.3,2.7,6.9,0.0,3.6,0.0,11.2,19.2,0.0,0.0,0.0,-0.007
15,Alex Len,SAC,48.0,0.0,9.2,0.617,0.000,0.641,0.617,14.7,0.037,11.3,21.2,16.1,14.4,1.2,6.8,22.0,11.8,0.6,0.7,1.3,0.138
16,Alondes Williams,MIA,7.0,0.0,2.3,0.250,0.000,0.500,0.250,-7.9,0.500,0.0,7.1,3.5,0.0,0.0,6.1,19.2,29.1,-0.1,0.0,-0.1,-0.357
17,Alperen Şengün,HOU,63.0,63.0,32.5,0.537,0.297,0.567,0.553,22.0,0.113,9.5,21.5,15.4,25.2,1.8,2.1,12.5,27.0,3.8,3.1,6.9,0.163
18,Amari Bailey,CHO,10.0,0.0,6.5,0.333,0.125,0.438,0.354,9.7,0.333,10.1,5.3,7.8,15.2,2.3,0.0,12.9,21.1,-0.1,0.0,-0.1,-0.044
19,Amen Thompson,HOU,62.0,23.0,22.4,0.536,0.138,0.595,0.545,18.2,0.130,11.3,20.4,15.8,17.0,2.7,2.5,14.9,18.5,1.9,2.4,4.3,0.149
20,Amir Coffey,LAC,70.0,13.0,20.9,0.472,0.380,0.571,0.571,10.0,0.523,2.3,8.9,5.7,6.8,1.4,0.9,7.9,12.5,1.6,1.0,2.6,0.084
21,Andre Drummond,CHI,79.0,10.0,17.1,0.556,0.000,0.560,0.556,23.0,0.006,21.5,37.4,29.3,4.1,2.7,3.6,12.3,21.3,2.3,2.6,4.9,0.175
22,Andre Jackson Jr.,MIL,57.0,8.0,10.0,0.500,0.370,0.611,0.585,8.5,0.460,8.4,13.1,10.8,10.8,1.3,0.9,21.1,10.0,0.5,0.5,1.0,0.081
23,Andrew Funk,CHI,5.0,0.0,2.6,0.000,0.000,0.000,0.000,-5.0,0.750,0.0,0.0,0.0,0.0,3.8,7.9,0.0,13.5,-0.1,0.0,-0.1,-0.252
24,Andrew Nembhard,IND,68.0,47.0,25.0,0.498,0.357,0.567,0.557,11.3,0.328,2.4,7.0,4.7,20.0,1.8,0.3,15.6,16.0,1.3,0.7,2.0,0.057
25,Andrew Wiggins,GSW,71.0,59.0,27.0,0.453,0.358,0.498,0.511,12.7,0.326,6.2,11.8,9.0,8.6,1.1,1.9,9.2,20.9,1.2,1.6,2.8,0.070
26,Anfernee Simons,POR,46.0,46.0,34.4,0.430,0.385,0.472,0.523,15.9,0.484,1.5,10.9,5.9,27.6,0.7,0.3,12.1,28.0,1.7,0.5,2.2,0.068
27,Anthony Black,ORL,69.0,33.0,16.9,0.466,0.394,0.510,0.540,8.4,0.381,3.3,10.8,7.0,10.6,1.5,1.7,16.6,12.7,0.1,1.5,1.6,0.067
28,Anthony Davis,LAL,76.0,76.0,35.5,0.556,0.271,0.582,0.567,25.8,0.083,10.4,28.3,19.8,15.5,1.6,5.7,9.5,26.7,7.2,4.7,11.8,0.210
29,Anthony Edwards,MIN,79.0,78.0,35.1,0.461,0.357,0.515,0.522,19.7,0.341,2.2,14.8,8.8,24.6,1.8,1.3,11.9,32.3,2.9,4.7,7.5,0.130
30,Anthony Gill,WAS,50.0,3.0,9.3,0.469,0.244,0.546,0.500,12.1,0.256,8.3,13.4,10.8,10.0,1.3,1.9,11.6,18.0,0.1,0.2,0.4,0.038
31,Armoni Brooks,BRK,10.0,0.0,10.4,0.326,0.344,0.286,0.446,8.3,0.696,7.2,11.9,9.5,6.9,0.5,0.9,6.0,20.8,-0.1,0.1,0.0,-0.018
32,Ashton Hagans,POR,19.0,1.0,16.6,0.408,0.320,0.457,0.465,8.5,0.352,4.7,11.7,8.0,23.7,1.7,2.6,27.7,14.6,-0.2,0.3,0.0,0.006
33,Ausar Thompson,DET,63.0,38.0,25.1,0.483,0.186,0.575,0.505,12.8,0.235,8.9,19.6,14.2,10.8,2.1,3.2,13.6,16.6,0.1,1.7,1.8,0.053
34,Austin Reaves,LAL,82.0,57.0,32.1,0.486,0.367,0.583,0.568,15.5,0.447,2.5,11.9,7.4,23.5,1.2,0.8,14.1,20.3,3.9,2.0,5.9,0.108
35,Ayo Dosunmu,CHI,76.0,37.0,29.1,0.501,0.403,0.568,0.583,13.4,0.410,2.7,8.3,5.5,15.6,1.5,1.7,11.9,17.2,2.6,1.5,4.1,0.089
36,Bam Adebayo,MIA,71.0,71.0,34.0,0.521,0.357,0.528,0.529,19.8,0.041,7.4,27.3,17.3,18.9,1.7,2.7,12.0,24.9,2.9,4.3,7.2,0.144
37,Ben Sheppard,IND,57.0,1.0,14.3,0.393,0.314,0.562,0.500,8.1,0.681,2.1,10.3,6.2,7.5,1.9,0.2,5.9,13.2,0.3,0.4,0.8,0.046
38,Ben Simmons,BRK,15.0,12.0,23.9,0.581,NaN,0.581,0.581,16.3,0.000,9.2,27.6,18.1,33.2,1.7,2.3,25.1,13.0,0.5,0.5,1.0,0.133
39,Bennedict Mathurin,IND,59.0,19.0,26.1,0.446,0.374,0.481,0.507,13.0,0.323,4.4,12.8,8.6,9.8,1.1,0.7,11.3,23.4,0.8,0.7,1.4,0.045
40,Bilal Coulibaly,WAS,63.0,15.0,27.2,0.435,0.346,0.502,0.509,8.9,0.428,3.4,12.8,8.0,8.2,1.6,2.3,15.1,14.2,-0.5,0.9,0.4,0.013
41,Bismack Biyombo,OKC,40.0,27.0,19.8,0.565,NaN,0.565,0.565,9.9,0.000,8.3,21.1,14.5,9.5,0.7,4.4,21.3,10.7,0.1,1.0,1.1,0.066
42,Blake Wesley,SAS,61.0,3.0,14.4,0.474,0.218,0.563,0.502,10.1,0.256,2.2,9.5,5.8,25.3,1.6,0.9,18.1,14.7,0.3,0.6,0.9,0.050
43,Boban Marjanović,HOU,14.0,0.0,5.1,0.529,0.000,0.563,0.529,21.1,0.059,10.5,38.2,24.2,13.9,0.7,2.6,11.1,27.0,0.1,0.1,0.2,0.128
44,Bobby Portis,MIL,82.0,4.0,24.5,0.508,0.407,0.545,0.562,17.5,0.268,7.9,24.8,16.6,7.8,1.6,1.4,8.6,22.9,2.1,2.6,4.7,0.112
45,Bogdan Bogdanović,ATL,79.0,33.0,30.4,0.428,0.374,0.503,0.537,14.7,0.583,2.3,10.3,6.2,14.9,1.9,1.0,8.7,22.3,2.8,1.2,3.9,0.079
46,Bojan Bogdanović,NYK,57.0,27.0,25.9,0.454,0.398,0.507,0.551,12.6,0.490,1.6,10.0,5.7,10.3,1.0,0.3,11.9,24.6,0.3,0.7,1.1,0.034
47,Bol Bol,PHO,43.0,0.0,10.9,0.616,0.423,0.717,0.689,18.7,0.344,8.1,24.1,16.5,5.3,1.0,4.7,10.7,16.5,1.0,0.7,1.6,0.168
48,Bones Hyland,LAC,37.0,5.0,14.6,0.386,0.326,0.457,0.474,10.8,0.538,1.1,10.1,5.7,24.5,2.4,0.7,14.4,24.8,-0.5,0.5,0.0,0.003
49,Bradley Beal,PHO,53.0,53.0,33.3,0.513,0.430,0.552,0.582,16.3,0.320,3.6,10.8,7.4,22.5,1.4,1.3,14.2,22.7,2.4,1.5,3.9,0.107

In [231]:

mvp.columns = mvp.columns.get_level_values(1)
mvp

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Nikola Jokić,28,DEN,79,926,990,0.935,79,34.6,26.4,12.4,9.0,1.4,0.9,0.583,0.359,0.817,17.0,0.299
1,2,Shai Gilgeous-Alexander,25,OKC,15,640,990,0.646,75,34.0,30.1,5.5,6.2,2.0,0.9,0.535,0.353,0.874,14.6,0.275
2,3,Luka Dončić,24,DAL,4,566,990,0.572,70,37.5,33.9,9.2,9.8,1.4,0.5,0.487,0.382,0.786,12.0,0.220
3,4,Giannis Antetokounmpo,29,MIL,1,192,990,0.194,73,35.2,30.4,11.5,6.5,1.2,1.1,0.611,0.274,0.657,13.2,0.246
4,5,Jalen Brunson,27,NYK,0,142,990,0.143,77,35.4,28.7,3.6,6.7,0.9,0.2,0.479,0.401,0.847,11.2,0.198
5,6,Jayson Tatum,25,BOS,0,86,990,0.087,74,35.7,26.9,8.1,4.9,1.0,0.6,0.471,0.376,0.833,10.4,0.189
6,7,Anthony Edwards,22,MIN,0,18,990,0.018,79,35.1,25.9,5.4,5.1,1.3,0.5,0.461,0.357,0.836,7.5,0.130
7,8,Domantas Sabonis,27,SAC,0,3,990,0.003,82,35.7,19.4,13.7,8.2,0.9,0.6,0.594,0.379,0.704,12.6,0.206
8,9,Kevin Durant,35,PHO,0,1,990,0.001,75,37.2,27.1,6.6,5.0,0.9,1.2,0.523,0.413,0.856,8.3,0.142

In [216]:
mvp.columns = mvp.columns.get_level_values(0)
mvp_ = mvp.loc[:, ['Player', 'Share']]
final_ = pd.merge(final, mvp_, how='outer').fillna(0)
final_2 = pd.merge(final_, team_, on='Team', how='left')
final_2.head(30)

KeyError: "None of [Index(['Player', 'Share'], dtype='object')] are in the [columns]"

In [8]:
def combine_tables(total, advanced, mvp, team):
    team = process_team(team)
    
    # total data processing
    total = total.loc[:, ['Player','Team','G','GS', 'MP','FG%','3P%','2P%', 'eFG%', 'FT%', 'TRB', 'AST', 'STL', 'BLK', 'PTS']].iloc[:-1]
    total['MP'] = round(total['MP']/total['G'], 1)
    total['TRB'] = round(total['TRB']/total['G'], 1)
    total['AST'] = round(total['AST']/total['G'], 1)
    total['STL'] = round(total['STL']/total['G'], 1)
    total['BLK'] = round(total['BLK']/total['G'], 1)
    total['PTS'] = round(total['PTS']/total['G'], 1)

    # advanced data processing
    advanced = advanced.loc[:,['Player', 'Team', 'PER', 'TS%','DRB%','TRB%','AST%','STL%','BLK%','USG%','OWS','DWS','BPM', 'VORP', 'WS','WS/48']].iloc[:-1]

    # mvp data processing
    mvp_ = mvp.copy()
    mvp_.columns = mvp_.columns.get_level_values(1)
    mvp_ = mvp_.loc[:, ['Player', 'Share']]
    
    # combine total and advanced and then mvp
    stats = pd.merge(total, advanced, how='outer')

    correct_teams = stats.drop_duplicates(subset=['Player'], keep='last', ignore_index=True)
    correct_teams = correct_teams.loc[:,['Player', 'Team']]
    stats = stats.drop_duplicates(subset=['Player'], keep='first', ignore_index=True)
    final = pd.merge(stats.drop(columns=('Team')), correct_teams, how='outer')
    cols = list(final.columns)
    cols.insert(1, cols.pop(cols.index("Team")))
    final = final[cols]

    
    final = pd.merge(final, mvp_, how='outer').fillna(0)
    final = pd.merge(final, team, on='Team', how='left')
    return final

done = combine_tables(total, advanced, mvp, team)

done.head(50)

,Player,Team,G,GS,MP,FG%,3P%,2P%,eFG%,FT%,...,USG%,OWS,DWS,BPM,VORP,WS,WS/48,Share,W/L%,Seed
0,A.J. Green,MIL,56.0,0.0,11.0,0.423,0.408,0.519,0.599,0.895,...,15.2,0.7,0.3,-2.1,0.0,1.1,0.084,0.000,0.598,3
1,A.J. Lawson,DAL,42.0,0.0,7.4,0.446,0.260,0.577,0.500,0.652,...,20.0,0.0,0.3,-4.6,-0.2,0.2,0.036,0.000,0.610,5
2,AJ Griffin,ATL,20.0,0.0,8.6,0.290,0.256,0.348,0.371,1.000,...,17.3,-0.4,0.0,-9.6,-0.3,-0.4,-0.120,0.000,0.439,10
3,Aaron Gordon,DEN,73.0,73.0,31.5,0.556,0.290,0.619,0.584,0.658,...,17.8,4.5,2.6,1.3,1.9,7.1,0.148,0.000,0.695,2
4,Aaron Holiday,HOU,78.0,1.0,16.3,0.446,0.387,0.510,0.547,0.921,...,16.7,1.3,1.2,-1.5,0.2,2.5,0.094,0.000,0.500,11
5,Aaron Nesmith,IND,72.0,47.0,27.7,0.496,0.419,0.581,0.606,0.781,...,16.0,2.8,1.3,-0.5,0.8,4.1,0.098,0.000,0.573,6
6,Aaron Wiggins,OKC,78.0,4.0,15.7,0.562,0.492,0.598,0.645,0.789,...,16.4,2.1,1.6,0.7,0.8,3.7,0.144,0.000,0.695,1
7,Adam Flagler,OKC,2.0,0.0,7.0,0.143,0.167,0.000,0.214,0.000,...,21.7,0.0,0.0,-10.6,0.0,0.0,-0.159,0.000,0.695,1
8,Adama Sanogo,CHI,9.0,0.0,7.3,0.519,0.000,0.519,0.519,0.667,...,24.8,0.1,0.1,-6.7,-0.1,0.2,0.133,0.000,0.476,9
9,Admiral Schofield,ORL,23.0,0.0,3.7,0.385,0.375,0.400,0.500,0.000,...,16.6,-0.1,0.1,-4.9,-0.1,0.0,0.006,0.000,0.573,5
10,Al Horford,BOS,65.0,33.0,26.8,0.511,0.419,0.658,0.640,0.867,...,12.0,3.5,2.7,3.6,2.5,6.2,0.172,0.000,0.780,1
11,Alec Burks,NYK,66.0,1.0,18.4,0.369,0.376,0.360,0.478,0.868,...,24.4,0.7,0.7,-2.3,-0.1,1.4,0.054,0.000,0.610,2
12,Aleksej Pokusevski,OKC,28.0,0.0,14.5,0.405,0.327,0.470,0.479,0.732,...,17.2,0.0,0.4,-1.9,0.0,0.4,0.050,0.000,0.695,1
13,Alex Caruso,CHI,71.0,57.0,28.7,0.468,0.408,0.563,0.593,0.760,...,14.7,2.3,2.6,2.5,2.3,4.9,0.115,0.000,0.476,9
14,Alex Fudge,LAL,6.0,0.0,6.7,0.400,0.200,0.500,0.433,1.000,...,19.2,0.0,0.0,-5.2,0.0,0.0,-0.007,0.000,0.573,8
15,Alex Len,SAC,48.0,0.0,9.2,0.617,0.000,0.641,0.617,0.588,...,11.8,0.6,0.7,0.2,0.2,1.3,0.138,0.000,0.561,9
16,Alondes Williams,MIA,7.0,0.0,2.3,0.250,0.000,0.500,0.250,1.000,...,29.1,-0.1,0.0,-23.2,-0.1,-0.1,-0.357,0.000,0.561,8
17,Alperen Şengün,HOU,63.0,63.0,32.5,0.537,0.297,0.567,0.553,0.693,...,27.0,3.8,3.1,4.9,3.5,6.9,0.163,0.000,0.500,11
18,Amari Bailey,CHO,10.0,0.0,6.5,0.333,0.125,0.438,0.354,0.857,...,21.1,-0.1,0.0,-8.3,-0.1,-0.1,-0.044,0.000,0.256,13
19,Amen Thompson,HOU,62.0,23.0,22.4,0.536,0.138,0.595,0.545,0.684,...,18.5,1.9,2.4,1.8,1.3,4.3,0.149,0.000,0.500,11
20,Amir Coffey,LAC,70.0,13.0,20.9,0.472,0.380,0.571,0.571,0.859,...,12.5,1.6,1.0,-2.2,-0.1,2.6,0.084,0.000,0.622,4
21,Andre Drummond,CHI,79.0,10.0,17.1,0.556,0.000,0.560,0.556,0.592,...,21.3,2.3,2.6,0.1,0.7,4.9,0.175,0.000,0.476,9
22,Andre Jackson Jr.,MIL,57.0,8.0,10.0,0.500,0.370,0.611,0.585,0.727,...,10.0,0.5,0.5,-3.6,-0.2,1.0,0.081,0.000,0.598,3
23,Andrew Funk,CHI,5.0,0.0,2.6,0.000,0.000,0.000,0.000,0.000,...,13.5,-0.1,0.0,-14.4,0.0,-0.1,-0.252,0.000,0.476,9
24,Andrew Nembhard,IND,68.0,47.0,25.0,0.498,0.357,0.567,0.557,0.804,...,16.0,1.3,0.7,-2.2,-0.1,2.0,0.057,0.000,0.573,6
25,Andrew Wiggins,GSW,71.0,59.0,27.0,0.453,0.358,0.498,0.511,0.751,...,20.9,1.2,1.6,-2.5,-0.3,2.8,0.070,0.000,0.561,10
26,Anfernee Simons,POR,46.0,46.0,34.4,0.430,0.385,0.472,0.523,0.916,...,28.0,1.7,0.5,0.2,0.8,2.2,0.068,0.000,0.256,15
27,Anthony Black,ORL,69.0,33.0,16.9,0.466,0.394,0.510,0.540,0.613,...,12.7,0.1,1.5,-3.0,-0.3,1.6,0.067,0.000,0.573,5
28,Anthony Davis,LAL,76.0,76.0,35.5,0.556,0.271,0.582,0.567,0.816,...,26.7,7.2,4.7,5.1,4.9,11.8,0.210,0.000,0.573,8
29,Anthony Edwards,MIN,79.0,78.0,35.1,0.461,0.357,0.515,0.522,0.836,...,32.3,2.9,4.7,3.3,3.7,7.5,0.130,0.018,0.683,3
30,Anthony Gill,WAS,50.0,3.0,9.3,0.469,0.244,0.546,0.500,0.806,...,18.0,0.1,0.2,-4.1,-0.3,0.4,0.038,0.000,0.183,14
31,Armoni Brooks,BRK,10.0,0.0,10.4,0.326,0.344,0.286,0.446,0.500,...,20.8,-0.1,0.1,-5.8,-0.1,0.0,-0.018,0.000,0.390,11
32,Ashton Hagans,POR,19.0,1.0,16.6,0.408,0.320,0.457,0.465,0.824,...,14.6,-0.2,0.3,-3.5,-0.1,0.0,0.006,0.000,0.256,15
33,Ausar Thompson,DET,63.0,38.0,25.1,0.483,0.186,0.575,0.505,0.597,...,16.6,0.1,1.7,-2.2,-0.1,1.8,0.053,0.000,0.171,15
34,Austin Reaves,LAL,82.0,57.0,32.1,0.486,0.367,0.583,0.568,0.853,...,20.3,3.9,2.0,0.4,1.6,5.9,0.108,0.000,0.573,8
35,Ayo Dosunmu,CHI,76.0,37.0,29.1,0.501,0.403,0.568,0.583,0.810,...,17.2,2.6,1.5,-0.8,0.7,4.1,0.089,0.000,0.476,9
36,Bam Adebayo,MIA,71.0,71.0,34.0,0.521,0.357,0.528,0.529,0.755,...,24.9,2.9,4.3,2.4,2.7,7.2,0.144,0.000,0.561,8
37,Ben Sheppard,IND,57.0,1.0,14.3,0.393,0.314,0.562,0.500,0.885,...,13.2,0.3,0.4,-3.4,-0.3,0.8,0.046,0.000,0.573,6
38,Ben Simmons,BRK,15.0,12.0,23.9,0.581,0.000,0.581,0.581,0.400,...,13.0,0.5,0.5,2.4,0.4,1.0,0.133,0.000,0.390,11
39,Bennedict Mathurin,IND,59.0,19.0,26.1,0.446,0.374,0.481,0.507,0.821,...,23.4,0.8,0.7,-3.4,-0.6,1.4,0.045,0.000,0.573,6
40,Bilal Coulibaly,WAS,63.0,15.0,27.2,0.435,0.346,0.502,0.509,0.702,...,14.2,-0.5,0.9,-4.2,-0.9,0.4,0.013,0.000,0.183,14
41,Bismack Biyombo,OKC,40.0,27.0,19.8,0.565,0.000,0.565,0.565,0.481,...,10.7,0.1,1.0,-3.4,-0.3,1.1,0.066,0.000,0.695,1
42,Blake Wesley,SAS,61.0,3.0,14.4,0.474,0.218,0.563,0.502,0.667,...,14.7,0.3,0.6,-4.0,-0.4,0.9,0.050,0.000,0.268,14
43,Boban Marjanović,HOU,14.0,0.0,5.1,0.529,0.000,0.563,0.529,0.643,...,27.0,0.1,0.1,-0.3,0.0,0.2,0.128,0.000,0.500,11
44,Bobby Portis,MIL,82.0,4.0,24.5,0.508,0.407,0.545,0.562,0.790,...,22.9,2.1,2.6,-0.8,0.6,4.7,0.112,0.000,0.598,3
45,Bogdan Bogdanović,ATL,79.0,33.0,30.4,0.428,0.374,0.503,0.537,0.921,...,22.3,2.8,1.2,0.2,1.4,3.9,0.079,0.000,0.439,10
46,Bojan Bogdanović,NYK,57.0,27.0,25.9,0.454,0.398,0.507,0.551,0.785,...,24.6,0.3,0.7,-3.2,-0.4,1.1,0.034,0.000,0.610,2
47,Bol Bol,PHO,43.0,0.0,10.9,0.616,0.423,0.717,0.689,0.789,...,16.5,1.0,0.7,2.1,0.5,1.6,0.168,0.000,0.598,6
48,Bones Hyland,LAC,37.0,5.0,14.6,0.386,0.326,0.457,0.474,0.783,...,24.8,-0.5,0.5,-3.6,-0.2,0.0,0.003,0.000,0.622,4
49,Bradley Beal,PHO,53.0,53.0,33.3,0.513,0.430,0.552,0.582,0.813,...,22.7,2.4,1.5,0.4,1.1,3.9,0.107,0.000,0.598,6

In [9]:
done.columns

Index(['Player', 'Team', 'G', 'GS', 'MP', 'FG%', '3P%', '2P%', 'eFG%', 'FT%',
       'TRB', 'AST', 'STL', 'BLK', 'PTS', 'PER', 'TS%', 'DRB%', 'TRB%', 'AST%',
       'STL%', 'BLK%', 'USG%', 'OWS', 'DWS', 'BPM', 'VORP', 'WS', 'WS/48',
       'Share', 'W/L%', 'Seed'],
      dtype='object')